name: C/C++ CI

on:
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v3

    - name: make 
      run:
        make -j666
        ./build_all.sh
        
